language: python
dist: xenial

env:
  global:
    - COVERALLS_PARALLEL=true

#python:
#  - "3.6"
#  - "3.7"

cache: pip

before_install:
  - export BOTO_CONFIG=/dev/null

stages:
  - Lint
  - Test
  - Document

install:
  - pip install jieba
  - pip install python-coveralls
  - pip install -e .
  - pip install tensorflow==1.14.0
  - pip install coverage
  - pip install nose
  - python -c "import kashgari;print(f'kashgari version {kashgari.__version__}')"
  - git fetch --unshallow --quiet

jobs:
  include:
    - stage: Lint
      python:
        - "3.6"
      install:
        - pip install flake8 flake8-builtins
      script:
        - flake8 kashgari

    - stage: Test
      python:
        - "3.6"
      script: nosetests --with-coverage --cover-html --cover-html-dir=htmlcov
        --cover-xml --cover-xml-file=coverage.xml --with-xunit
        --cover-package="kashgari"
        tests/labeling/
      name: "Labeling Model Tests"

    - script: nosetests --with-coverage --cover-html --cover-html-dir=htmlcov
        --cover-xml --cover-xml-file=coverage.xml --with-xunit
        --cover-package="kashgari"
        tests/labeling/

      python:
        - "3.7"
        - "3.6"
      name: "Labeling Model Tests"

    - script: nosetests --with-coverage --cover-html --cover-html-dir=htmlcov
              --cover-xml --cover-xml-file=coverage.xml --with-xunit
              --cover-package="kashgari"
              tests/classification/test_cnn_lstm.py
              tests/classification/test_cnn_gru.py
              tests/classification/test_cnn.py
              tests/classification/test_kmax_cnn.py

      name: "Classification Model Tests-1"

    - script: nosetests --with-coverage --cover-html --cover-html-dir=htmlcov
              --cover-xml --cover-xml-file=coverage.xml --with-xunit
              --cover-package="kashgari"
              tests/classification/test_r_cnn.py
              tests/classification/test_dropout_bigru.py
              tests/classification/test_avcnn.py
              tests/classification/test_bi_gru.py

      name: "Classification Model Tests-2"

    - script: nosetests --with-coverage --cover-html --cover-html-dir=htmlcov
              --cover-xml --cover-xml-file=coverage.xml --with-xunit
              --cover-package="kashgari"
              tests/classification/test_dpcnn.py
              tests/classification/test_bi_lstm.py
              tests/classification/test_avrnn_model.py
              tests/classification/test_dropout_avrnn.py

      name: "Classification Model Tests-3"

    - script: nosetests --with-coverage --cover-html --cover-html-dir=htmlcov
        --cover-xml --cover-xml-file=coverage.xml --with-xunit
        --cover-package="kashgari"
              tests/test_callbacks.py tests/test_corpus.py tests/test_processor.py
      name: "Callbacks Corpus Processor Test"

    - script: nosetests --with-coverage --cover-html --cover-html-dir=htmlcov
          --cover-xml --cover-xml-file=coverage.xml --with-xunit
          --cover-package="kashgari"
          tests/test_custom_multi_output_classification.py

      name: "Custom Multi-Output Model Tests"

    - script: nosetests --with-coverage --cover-html --cover-html-dir=htmlcov
        --cover-xml --cover-xml-file=coverage.xml --with-xunit
        --cover-package="kashgari"
        tests/embedding/

      name: "Embeddings Tests"

      after_script:
        - coveralls

      notifications:
        webhooks: https://coveralls.io/webhook

    - stage: Document
      python:
        - "3.6"
      install:
        - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc
        - pip install mkdocs mkdocs-material pymdown-extensions
      script:
        - cd mkdocs
        - mkdocs gh-deploy --force --clean
      branches:
        only:
          - master
