language: python
dist: xenial

env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
    - TEST_FILE="tests/test_seq2seq/"
    - TEST_FILE="tests/test_labeling/test_bi_gru_model.py tests/test_labeling/test_bi_lstm_model.py tests/test_labeling/test_cnn_lstm_model.py"
    - TEST_FILE="tests/test_labeling/test_bi_gru_crf_model.py tests/test_labeling/test_bi_lstm_crf_model.py"
    - TEST_FILE="tests/test_classification/"
    - TEST_FILE="tests/test_embeddings/"
    - TEST_FILE="tests/test_processor/"
    - TEST_FILE="tests/test_corpus.py tests/test_utils.py"

cache: pip

stages:
  - Lint
  - Test
  - Test2_1
  - Test2_2

after_script:
  - coveralls

notifications:
  webhooks: https://coveralls.io/webhook

jobs:
  include:
    - stage: Lint
      python: "3.6"
      install:
        - pip install -r requirements.dev.txt
      script:
        - sh ./scripts/lint.sh
    - stage: Test
      name: Test @ TensorFlow 2.0.0
      python: "3.6"
      before_install:
        - export BOTO_CONFIG=/dev/null
      install:
        - pip install -r requirements.dev.txt
        - pip install -r requirements.txt
        - pip install tensorflow==2.0.0
        - python -c "import kashgari;print(f'kashgari version {kashgari.__version__}')"
        - export PYTHONPATH=`pwd`
      script: pytest --doctest-modules --junitxml=test-reports/junit.xml
        --cov=kashgari --cov-report=xml:coverage.xml --cov-report=html:htmlcov --cov-config .coveragerc
        $TEST_FILE
    - stage: Test2_1
      name: Test @ TensorFlow 2.1.0
      python: "3.6"
      before_install:
        - export BOTO_CONFIG=/dev/null
      install:
        - pip install -r requirements.dev.txt
        - pip install -r requirements.txt
        - pip install tensorflow==2.1.0
        - python -c "import kashgari;print(f'kashgari version {kashgari.__version__}')"
        - export PYTHONPATH=`pwd`
      script: pytest --doctest-modules --junitxml=test-reports/junit.xml
        --cov=kashgari --cov-report=xml:coverage.xml --cov-report=html:htmlcov --cov-config .coveragerc
        $TEST_FILE
    - stage: Test2_2
      name: Test @ TensorFlow 2.2.0
      python: "3.6"
      before_install:
        - export BOTO_CONFIG=/dev/null
      install:
        - pip install -r requirements.dev.txt
        - pip install -r requirements.txt
        - pip install tensorflow==2.2.0
        - python -c "import kashgari;print(f'kashgari version {kashgari.__version__}')"
        - export PYTHONPATH=`pwd`
      script: pytest --doctest-modules --junitxml=test-reports/junit.xml
        --cov=kashgari --cov-report=xml:coverage.xml --cov-report=html:htmlcov --cov-config .coveragerc
        $TEST_FILE

