site_name: Kashgari
theme:
  name: "material"
  #  font: false
  feature:
    tabs: true
  palette:
    primary: red
    accent: red
  language: "en"
repo_url: https://github.com/BrikerMan/Kashgari

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: "#"
  # pymdown-extensions
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: none
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.highlight:
      # css_class: codehilite # https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml
      extend_pygments_lang:
        - name: python
          lang: python
          options:
            startinline: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - static/css/extra.css

plugins:
  - search

extra:
  social:
    - type: github-alt
      link: https://github.com/BrikerMan

nav:
  - Home:
      - "index.md"
  - Tutorials:
      - tutorial/language_embedding.md
      - tutorial/text_classification_model.md
      - tutorial/text_labeling_model.md
  - Advanced:
      - customize_multi_output_model.md
      - deal_with_numeric_features.md
      - tensorflow_serving.md
  - API:
      - "corpus.md"
  - About:
      - "CONTRIBUTING.md"
      - "Release Notes": "CHANGELOG.md"
